# Generated by Django 4.1.3 on 2023-06-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=100)),
                ('room_id', models.CharField(max_length=150)),
                ('players', models.TextField()),
            ],
        ),
    ]
